-- MySQL Script generated by MySQL Workbench
-- 04/06/16 00:46:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema schoolsoft
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schoolsoft` ;

-- -----------------------------------------------------
-- Schema schoolsoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schoolsoft` DEFAULT CHARACTER SET latin1 ;
USE `schoolsoft` ;

-- -----------------------------------------------------
-- Table `schoolsoft`.`schooluser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`schooluser` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`schooluser` (
  `username` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `admin` TINYINT(4) NOT NULL,
  `student` TINYINT(4) NOT NULL,
  `employee` TINYINT(4) NOT NULL,
  `hashed_password` VARCHAR(45) NOT NULL,
  `reset_password_code` VARCHAR(45) NOT NULL,
  `reset_password_code_until` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `school_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `userschoolfk`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `email` ON `schoolsoft`.`schooluser` (`email` ASC);

CREATE INDEX `schoolindex` ON `schoolsoft`.`schooluser` (`school_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`school` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`school` (
  `schoolid` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`schoolid`),
  CONSTRAINT `adminkey`
    FOREIGN KEY (`admin_id`)
    REFERENCES `schoolsoft`.`schooluser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `name_UNIQUE` ON `schoolsoft`.`school` (`name` ASC);

CREATE INDEX `adminkey_idx` ON `schoolsoft`.`school` (`admin_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`parent` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`parent` (
  `parentid` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `relation` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `office_phone1` VARCHAR(45) NULL DEFAULT NULL,
  `office_phone2` VARCHAR(45) NULL DEFAULT NULL,
  `mobile_phone` VARCHAR(45) NULL DEFAULT NULL,
  `office_address` VARCHAR(100) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `occupation` VARCHAR(45) NULL DEFAULT NULL,
  `education` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `school_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `student_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`parentid`),
  CONSTRAINT `school`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student`
    FOREIGN KEY (`student_id`)
    REFERENCES `schoolsoft`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `schoolsoft`.`schooluser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `student_idx` ON `schoolsoft`.`parent` (`student_id` ASC);

CREATE INDEX `user_idx` ON `schoolsoft`.`parent` (`user_id` ASC);

CREATE INDEX `school_idx` ON `schoolsoft`.`parent` (`school_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`batch` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`batch` (
  `batchid` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `is_active` TINYINT(4) NOT NULL DEFAULT '1',
  `school_id` INT(11) NOT NULL,
  `grading_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`batchid`),
  CONSTRAINT `batchschool`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `batchschool_idx` ON `schoolsoft`.`batch` (`school_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`student` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`student` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(4100) NOT NULL,
  `admission_no` VARCHAR(100) NOT NULL,
  `admission_date` DATE NOT NULL,
  `roll_no` VARCHAR(100) NOT NULL,
  `batch_id` INT(11) NULL DEFAULT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` TINYINT(4) NOT NULL,
  `blood_group` VARCHAR(10) NULL DEFAULT NULL,
  `birth_place` VARCHAR(100) NULL DEFAULT NULL,
  `nationality_id` INT(11) NULL DEFAULT NULL,
  `language` VARCHAR(100) NULL DEFAULT NULL,
  `religion` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(100) NULL DEFAULT NULL,
  `pin_code` VARCHAR(100) NULL DEFAULT NULL,
  `country_id` INT(11) NULL DEFAULT NULL,
  `phone1` VARCHAR(45) NOT NULL,
  `phone2` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `photo_filename` VARCHAR(45) NULL DEFAULT NULL,
  `photo_content_type` VARCHAR(10) NULL DEFAULT NULL,
  `photo_data` BLOB NULL DEFAULT NULL,
  `is_sms_enabled` TINYINT(4) NULL DEFAULT '1',
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `parent_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `school_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `parentpk`
    FOREIGN KEY (`parent_id`)
    REFERENCES `schoolsoft`.`parent` (`parentid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `schoolstundent`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_batch_pk`
    FOREIGN KEY (`batch_id`)
    REFERENCES `schoolsoft`.`batch` (`batchid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `schoolsoft`.`schooluser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `student_id_UNIQUE` ON `schoolsoft`.`student` (`student_id` ASC);

CREATE INDEX `schoolid` ON `schoolsoft`.`student` (`school_id` ASC);

CREATE INDEX `firstname` ON `schoolsoft`.`student` (`first_name` ASC, `last_name`(767) ASC);

CREATE INDEX `userid_idx` ON `schoolsoft`.`student` (`user_id` ASC);

CREATE INDEX `student_batch_pk_idx` ON `schoolsoft`.`student` (`batch_id` ASC);

CREATE INDEX `parentpk_idx` ON `schoolsoft`.`student` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`attendance` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`attendance` (
  `attendanceid` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `day_date` DATE NOT NULL,
  `school_id` INT(11) NOT NULL,
  `morning` TINYINT(4) NOT NULL,
  `afternoon` TINYINT(4) NOT NULL,
  PRIMARY KEY (`attendanceid`),
  CONSTRAINT `attschoolfk`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attstudentfk`
    FOREIGN KEY (`student_id`)
    REFERENCES `schoolsoft`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `studentfk_idx` ON `schoolsoft`.`attendance` (`student_id` ASC);

CREATE INDEX `attschoolfk_idx` ON `schoolsoft`.`attendance` (`school_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`subject` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`subject` (
  `subjectid` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `schoolid` INT(11) NOT NULL,
  `is_active` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`subjectid`),
  CONSTRAINT `subjectschoolid`
    FOREIGN KEY (`schoolid`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `subjectschoolid_idx` ON `schoolsoft`.`subject` (`schoolid` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`batch_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`batch_subject` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`batch_subject` (
  `batch_subject_id` INT(11) NOT NULL,
  `batch_id` INT(11) NOT NULL,
  `subject_id` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  PRIMARY KEY (`batch_subject_id`),
  CONSTRAINT `batchfk`
    FOREIGN KEY (`batch_id`)
    REFERENCES `schoolsoft`.`batch` (`batchid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subjectfk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `schoolsoft`.`subject` (`subjectid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `batchfk_idx` ON `schoolsoft`.`batch_subject` (`batch_id` ASC);

CREATE INDEX `subjectfk_idx` ON `schoolsoft`.`batch_subject` (`subject_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`exam_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`exam_group` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`exam_group` (
  `examgroupid` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `batch_id` INT(11) NULL DEFAULT NULL,
  `exam_type` VARCHAR(45) NULL DEFAULT NULL,
  `exam_group_start_date` DATE NOT NULL,
  `exam_group_end_date` DATE NOT NULL,
  `schoolid` INT(11) NULL DEFAULT NULL,
  `is_final_exam` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`examgroupid`),
  CONSTRAINT `examgroupbatch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `schoolsoft`.`batch` (`batchid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `examgroup_school`
    FOREIGN KEY (`schoolid`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `examgroup_school_idx` ON `schoolsoft`.`exam_group` (`schoolid` ASC);

CREATE INDEX `examgroupbatch_idx` ON `schoolsoft`.`exam_group` (`batch_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`exam` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`exam` (
  `examid` INT(11) NOT NULL,
  `exam_group_id` INT(11) NOT NULL,
  `subject_id` INT(11) NOT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `maximum_marks` DOUBLE NOT NULL,
  `minimum_marks` DOUBLE NOT NULL,
  `grading_level_id` INT(11) NOT NULL,
  `weightage` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `school_id` INT(11) NOT NULL,
  PRIMARY KEY (`examid`),
  CONSTRAINT `examgroup`
    FOREIGN KEY (`exam_group_id`)
    REFERENCES `schoolsoft`.`exam_group` (`examgroupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `examsubjectfk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `schoolsoft`.`subject` (`subjectid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_exam`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `school_idx` ON `schoolsoft`.`exam` (`school_id` ASC);

CREATE INDEX `examgroup_idx` ON `schoolsoft`.`exam` (`exam_group_id` ASC);

CREATE INDEX `examsubjectfk_idx` ON `schoolsoft`.`exam` (`subject_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`grading_levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`grading_levels` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`grading_levels` (
  `gradingid` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `batch_id` INT(11) NOT NULL,
  `min_score` INT(11) NOT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `school_id` INT(11) NOT NULL,
  `credit_points` DOUBLE NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`gradingid`),
  CONSTRAINT `gradbatchfk`
    FOREIGN KEY (`batch_id`)
    REFERENCES `schoolsoft`.`batch` (`batchid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grading_school`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `grading_school_idx` ON `schoolsoft`.`grading_levels` (`school_id` ASC);

CREATE INDEX `gradbatchfk_idx` ON `schoolsoft`.`grading_levels` (`batch_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`exam_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`exam_score` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`exam_score` (
  `examscoreid` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `exam_id` INT(11) NOT NULL,
  `marks` DOUBLE NOT NULL,
  `grading_level_id` INT(11) NOT NULL,
  `remarks` VARCHAR(45) NULL DEFAULT NULL,
  `is_passed` TINYINT(4) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `school_id` INT(11) NOT NULL,
  PRIMARY KEY (`examscoreid`),
  CONSTRAINT `exam_examscore`
    FOREIGN KEY (`exam_id`)
    REFERENCES `schoolsoft`.`exam` (`examid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gradingfk`
    FOREIGN KEY (`grading_level_id`)
    REFERENCES `schoolsoft`.`grading_levels` (`gradingid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `schoolexamscore`
    FOREIGN KEY (`school_id`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_exam_score`
    FOREIGN KEY (`student_id`)
    REFERENCES `schoolsoft`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `schoolexamscore_idx` ON `schoolsoft`.`exam_score` (`school_id` ASC);

CREATE INDEX `student_exam_score_idx` ON `schoolsoft`.`exam_score` (`student_id` ASC);

CREATE INDEX `exam_examscore_idx` ON `schoolsoft`.`exam_score` (`exam_id` ASC);

CREATE INDEX `gradingfk_idx` ON `schoolsoft`.`exam_score` (`grading_level_id` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`teacher` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`teacher` (
  `teacherid` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` TINYINT(4) NOT NULL DEFAULT '1',
  `qualification` VARCHAR(100) NOT NULL,
  `experience_detail` VARCHAR(200) NULL DEFAULT NULL,
  `experienceyears` DOUBLE NOT NULL,
  `is_active` TINYINT(4) NOT NULL DEFAULT '1',
  `date_of_birth` DATE NOT NULL,
  `blood_group` VARCHAR(10) NOT NULL,
  `home_address` VARCHAR(100) NOT NULL,
  `photo_filename` VARCHAR(45) NULL DEFAULT NULL,
  `photo_file` BLOB NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NOT NULL,
  `mobile2` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `schoolid` INT(11) NOT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`teacherid`),
  CONSTRAINT `teacherschoolpk`
    FOREIGN KEY (`schoolid`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teacheruserfk`
    FOREIGN KEY (`userid`)
    REFERENCES `schoolsoft`.`schooluser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `teacherschoolpk_idx` ON `schoolsoft`.`teacher` (`schoolid` ASC);

CREATE INDEX `teacheruserfk_idx` ON `schoolsoft`.`teacher` (`userid` ASC);


-- -----------------------------------------------------
-- Table `schoolsoft`.`timetable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolsoft`.`timetable` ;

CREATE TABLE IF NOT EXISTS `schoolsoft`.`timetable` (
  `timetableid` INT(11) NOT NULL,
  `weekday` VARCHAR(45) NOT NULL,
  `start_time` VARCHAR(45) NOT NULL,
  `end_time` VARCHAR(45) NOT NULL,
  `subject_id` INT(11) NOT NULL,
  `teacher_id` INT(11) NOT NULL,
  `batch_id` INT(11) NOT NULL,
  `schoolid` INT(11) NOT NULL,
  PRIMARY KEY (`timetableid`),
  CONSTRAINT `timetablebatchfk`
    FOREIGN KEY (`batch_id`)
    REFERENCES `schoolsoft`.`batch` (`batchid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `timetableschoolidfk`
    FOREIGN KEY (`schoolid`)
    REFERENCES `schoolsoft`.`school` (`schoolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `timetablesubjectfk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `schoolsoft`.`subject` (`subjectid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `timetableteacherfk`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `schoolsoft`.`teacher` (`teacherid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `timetableschoolidfk_idx` ON `schoolsoft`.`timetable` (`schoolid` ASC);

CREATE INDEX `timetablebatchfk_idx` ON `schoolsoft`.`timetable` (`batch_id` ASC);

CREATE INDEX `timetablesubjectfk_idx` ON `schoolsoft`.`timetable` (`subject_id` ASC);

CREATE INDEX `timetableteacherfk_idx` ON `schoolsoft`.`timetable` (`teacher_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
